#!/bin/sh

set -e

echo "🚀 Running pre-commit hook 🚀"

echo -e "\n🔍 Running linter..."
npm run lint

echo -e "\n🔨 Building project..."
npm run build

echo -e "\n📦 Adding the dist/index.js file..."
git add dist/index.js

echo -e "\n🎉 Pre-commit status: success 🎉\n"
