name: 'Update Tags'
description: 'Updates tags for the repository using semantic versioning'
inputs:
  version:
    description: 'Set specific version'
    required: false
  type:
    description: 'Type of version increment. Available options: major, minor, patch'
    required: false
    default: 'patch'
  skip-push:
    description: 'Skip pushing the tags to remote repository'
    required: false
    default: false
outputs:
  version:
    description: 'Version that was set'
  previous_version:
    description: 'Previous version'
runs:
  using: 'node20'
  main: 'dist/index.js'
