name: 'Update tags'
description: 'Updates tags in a repository using semantic versioning'

inputs:
  version:
    description: 'specific version'
    required: false
    type: string
  update-type:
    description: 'version update type'
    required: false
    default: 'patch'
    type: choice
    options:
      - patch
      - minor
      - major
  path:
    description: 'path to place the action in'
    required: false
    default: './actions/update-tags'
    type: string
  email:
    description: 'email to use for git'
    required: true
    type: string
  name:
    description: 'name to use for git'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        repository: dae-ne/update-tags
        path: ${{ inputs.path }}
    - name: Set up Git
      run: |
        git config user.email ${{ inputs.email }}
        git config user.name ${{ inputs.name }}
      shell: bash
    - name: Add permissions
      run: |
        chmod +x ${{ inputs.path }}/update-tags-script/update_tags.sh
      shell: bash
    - name: Run script
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          ${{ inputs.path }}/update-tags-script/update_tags.sh -f -t ${{ inputs.update-type }}
        else
          ${{ inputs.path }}/update-tags-script/update_tags.sh -f -v ${{ inputs.version }} -t ${{ inputs.update-type }}
        fi
      shell: bash
