name: 'Get MSBuild project version'
description: 'Reads MSBuild project version from .proj (.csproj, .vbproj, .dbproj, etc.) files'
inputs:
  validate-all:
    description: 'Validate all version parts'
    required: false
    default: false
outputs:
  version-prefix:
    description: 'Version prefix'
runs:
  using: 'node20' # TODO: check if the version is correct
  main: 'dist/index.js'
